#!/bin/bash
BASE_OPTIONS="-g";

if [ -z $1 ]; then
 echo "Recherche vide!";
 exit;
fi
if [ ! -z $2 ]; then
    OPTIONS=$2;
fi
  OPTIONS="$OPTIONS $BASE_OPTIONS";
  SEARCHED=$1;
  echo "Ack as $ACK";
  echo "Search in ${PWD}";
  echo "-options: $OPTIONS";
  echo "-criter: \"$1\"";
  eval $ACK $OPTIONS "$SEARCHED" ${PWD} | xargs bash -c '</dev/tty vim -p "$@"' ignoreme;
