#!/bin/bash
BASE_OPTIONS="--match";

if [ -z $1 ]; then
 echo "Recherche vide!";
 exit;
fi
if [ ! -z $2 ]; then
    TARGET_PATH=${PWD}/$2;
fi
  SEARCHED=$1;
  echo "Search in $TARGET_PATH";
  echo "-criter:\"$1\"";
  ack-grep $BASE_OPTIONS "$SEARCHED" $TARGET_PATH;
