#!/bin/bash
. "/home/ludovic/my-tools/search/conf"
BASE_OPTIONS="--ignore-dir=cache --ignore-dir=log --ignore-dir=vendor -g";

if [ -z $1 ]; then
 echo "Recherche vide!";
 exit;
fi
if [ ! -z $2 ]; then
 if [ $2 == "--sf" ]; then
    PROJECT_HOME="$PROJECT_HOME/lib/vendor"
  else
    OPTIONS=$2;
  fi
fi
  OPTIONS="$OPTIONS $BASE_OPTIONS";
  SEARCHED=$1;
  echo "Search in t-resa";
  echo "-options: $OPTIONS";
  echo "-criter: \"$1\"";
  ack-grep $OPTIONS "$SEARCHED" $PROJECT_HOME;
