#!/bin/bash
BASE_OPTIONS="--match";

if [ -z $1 ]; then
 echo "Recherche vide!";
 exit;
fi
if [ ! -z $2 ]; then
    OPTIONS=$2;
fi

  OPTIONS="$OPTIONS $BASE_OPTIONS";
  SEARCHED="function $1";
  echo "Search in ${PWD}";
  echo "-options: $OPTIONS";
  echo "-criter: \"$1\"";
  $ACK $OPTIONS "$SEARCHED" ${PWD};
