#!/bin/bash
BASE_OPTIONS="--match";

if [ -z $1 ]; then
 echo "Recherche vide!";
 exit;
fi
if [ ! -z $2 ]; then
    if [ $2 = *[--]* ]; then
        OPTIONS=$2;
    else
        OPTIONS="";
        PWD=$2;
    fi

fi
if [ ! -z $3 ]; then
    PWD=$3;
fi

  OPTIONS="$OPTIONS $BASE_OPTIONS";
  SEARCHED_JS="function $1";
  SEARCHED_PYTHON="def $1";
  echo "Search in ${PWD}";
  echo "-options: $OPTIONS";
  echo "-criter: \"$1\"";
  $ACK --type=js $OPTIONS "$SEARCHED_JS" ${PWD};
  $ACK --type=python $OPTIONS "$SEARCHED_PYTHON" ${PWD};
