alias ll="ls -al"
alias srchfile="~/my-tools/search/srchfile"
alias srchfct="~/my-tools/search/srchfct"
alias srchstr="~/my-tools/search/srch"
alias gen-gh-pages="~/my-tools/git/create-gh-pages"
alias upd-gh-pages="~/my-tools/git/github/update-gh-pages"
alias sf-build="symfony propel:build --all --and-load --no-confirmation"
alias sf-build-test="symfony propel:build --all --and-load --env=test --no-confirmation"
alias sf-test="symfony test:all"
alias sf-build-all-and-test="symfony propel:build --all --and-load --no-confirmation;symfony propel:build --all --and-load --env=test --no-confirmation;symfony cc;symfony test:all"
alias sf-build-all="symfony propel:build --all --and-load --no-confirmation;symfony propel:build --all --and-load --env=test --no-confirmation;symfony cc"
alias dev-term="gnome-terminal --tab --title=actions --tab --title=tmpl --tab --title=form --tab --title=conf"
